### PR TITLE
Code updates

### PR DESCRIPTION
**Pull request by reedy**
* Raise PHP requirement to >=7.1
* Update phpunit/phpunit to ^8.5
* Pin monolog/monolog to ^1.2.0 (for now)
* Add initial GitHub Actions CI
** cf https://github.com/Krinkle/bloom-filter/blob/c2c370a4ab6d1c5253899002089f045bbcde8d85/.github/workflows/CI.yaml and updated
* Add required PHP extensions to composer.json `require`

From testing locally, the only errors/warnings I see are https://github.com/liuggio/statsd-php-client/issues/60 (not included in this chain, and GitHub dependancies suck), and https://github.com/liuggio/statsd-php-client/issues/62

This is probably still WIP...

PHP requirement should probably be raised to >= 7.2 as that's what we're testing, and the `monolog/monolog` dependancy probably wants pinning higher. The original unbounded ">=1.2.0" resulted in 3.2.0 being installed, which had some decleration mismatches.

```
PHP Fatal error:  Declaration of Liuggio\StatsdClient\Monolog\Formatter\StatsDFormatter::format(array $record) must be compatible with Monolog\Formatter\LineFormatter::format(Monolog\LogRecord $record): string in /Users/reedy/PhpstormProjects/statsd-php-client/src/Liuggio/StatsdClient/Monolog/Formatter/StatsDFormatter.php on line 61

Fatal error: Declaration of Liuggio\StatsdClient\Monolog\Formatter\StatsDFormatter::format(array $record) must be compatible with Monolog\Formatter\LineFormatter::format(Monolog\LogRecord $record): string in /Users/reedy/PhpstormProjects/statsd-php-client/src/Liuggio/StatsdClient/Monolog/Formatter/StatsDFormatter.php on line 61
```

There's also various other code updates that probably would be useful to happen, but don't need to be in this more minimal patch to "get things working" again.

### CODE REVIEW

**Comment by dav-m85** [comment]
Hi @reedy, thanks for pinging and sending a PR to this repo. I'll have a look before the weekend :)

**Comment by reedy** [comment]
Thanks!

FWIW, I tried to email you, but it seems the address on your website is wrong (possibly for spam reasons?), and also when I fixed the address to match the domain of the website itself, that seems to not work either.

**Review by dav-m85 — APPROVED** [review]
Thanks for the Github CI move, and update deps.

**Comment by dav-m85** [comment]
I plan to [release a new minor after all pending PRs](https://interfacegraphique08-gcarrier.profweb.ca/) are merged. Thanks for your help!

**Comment by reedy** [comment]
Thanks!

Do we want to raise the required PHP version further to >= 7.2 so we know we're testing on the versions we claim to support?

Probably need to look a little more at `monolog/monolog`, and update the code to account for that, we can allow `^2` probably with minimal/minor changes...

**Pull request merged**
